[pytest]
minversion = 6.0
addopts = -ra
markers =
    ui: mark UI tests
    ui_negative: mark negative UI tests
    api: mark API tests
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

